FROM mcr.microsoft.com/dotnet/sdk:5.0

ADD .gen/httpserver scripts/dnsgames_init /
ADD csharp-http/Program.cs /
ADD csharp-http/Dns.csproj /

ENTRYPOINT ["/dnsgames_init"]
CMD ["dotnet", "run Dns.dll"]