# https://hub.docker.com/_/microsoft-dotnet
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /source

# copy csproj 
COPY *.csproj .

# copy and publish app and libraries
COPY . .
RUN dotnet publish Dns.csproj -c release -o /app --no-restore

# final stage/image
FROM mcr.microsoft.com/dotnet/runtime:5.0
WORKDIR /app
COPY --from=build /app .
ADD .gen/httpserver scripts/dnsgames_init /

ENTRYPOINT ["/dnsgames_init"]
RUN dotnet run Dns.dll
